"""Phase 4 - Inspection report generator.

Produces a client-style PDF per scan: header + scan metadata, an auto-written
plain-language findings summary, a table of confirmed defects, the 3D render,
and 2D slice views of the most severe defects.

The report is written from the *confirmed* detections (post human-in-the-loop
review) and is deliberately blind to ground truth - a real inspection
deliverable would not have a planted-defect key. Detection-quality metrics
(recall/precision) live in the README, not in a per-scan client report.

Run:  ``python report.py --vol vol_000``   (needs detect + classify + visualize first)
"""

from __future__ import annotations

import argparse
from datetime import datetime

from fpdf import FPDF

import common
from common import TYPE_COLORS, DATA_DIR, MANIFESTS_DIR
from detect import DETECTIONS_DIR
from visualize import RENDERS_DIR, SLICES_DIR, REVIEWS_DIR

REPORTS_DIR = DATA_DIR / "reports"

NAVY = (23, 42, 70)
LIGHT = (232, 236, 243)
GREY = (110, 110, 110)
SEV_COLORS = {"high": (215, 25, 28), "medium": (219, 140, 40), "low": (26, 150, 65)}


def _hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


class ReportPDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return  # first page has its own title block
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GREY)
        self.cell(0, 6, "VoxelScan Inspection Report  -  SIMULATED data", align="L")
        self.ln(8)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GREY)
        self.cell(0, 6, f"Page {self.page_no()}  -  generated by VoxelScan (synthetic data)",
                  align="C")


# ---------------------------------------------------------------------------
# Findings text (factual, no overclaiming)
# ---------------------------------------------------------------------------
def _findings_text(vol_id, confirmed) -> str:
    if not confirmed:
        return (f"No defects were confirmed in simulated scan {vol_id} after review. "
                f"The automated detector reported no anomalies exceeding the "
                f"confidence thresholds.")

    n = len(confirmed)
    by_type = {}
    sev_counts = {"high": 0, "medium": 0, "low": 0}
    for d in confirmed:
        by_type[d["final_type"]] = by_type.get(d["final_type"], 0) + 1
        sev_counts[d["severity_label"]] += 1
    type_str = ", ".join(f"{c} {t}" + ("" if c == 1 else "s") for t, c in sorted(by_type.items()))

    worst = max(confirmed, key=lambda d: d["severity_score"])
    z, y, x = worst["center_zyx"]

    parts = [
        f"Automated analysis of simulated scan {vol_id}, followed by "
        f"human-in-the-loop review, confirmed {n} defect"
        f"{'' if n == 1 else 's'}: {type_str}.",
        f"By severity index (equivalent size x intensity deviation), "
        f"{sev_counts['high']} rank high, {sev_counts['medium']} medium, and "
        f"{sev_counts['low']} low.",
        f"The most significant confirmed feature is a {worst['final_type']} "
        f"centred at (z={z:.0f}, y={y:.0f}, x={x:.0f}) with an equivalent "
        f"diameter of {worst['equivalent_diameter']:.1f} voxels and a peak "
        f"intensity deviation of {worst['intensity_delta']:+.0f} from the local "
        f"baseline.",
        "All figures are measurements from automated detection on simulated "
        "volumetric scan data; this report characterises the analysis workflow "
        "and does not model acoustic physics or represent a real asset.",
    ]
    return " ".join(parts)


# ---------------------------------------------------------------------------
# PDF sections
# ---------------------------------------------------------------------------
def _title_block(pdf, vol_id, manifest):
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_xy(12, 8)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, "VoxelScan  Inspection Report")
    pdf.set_xy(12, 18)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Scan {vol_id}   |   generated {datetime.now():%Y-%m-%d %H:%M}")
    pdf.set_xy(12, 24)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "SIMULATED volumetric scan data - analysis workflow demo, not a real asset "
                   "and not calibrated acoustics.")
    pdf.set_y(38)
    pdf.set_text_color(0, 0, 0)


def _kv_section(pdf, title, rows):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    for k, v in rows:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(55, 6, f"  {k}")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, str(v), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)


def _findings_section(pdf, vol_id, confirmed):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, "Findings summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5.5, _findings_text(vol_id, confirmed))
    pdf.ln(3)


def _defects_table(pdf, confirmed):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, "Confirmed defects", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)

    headers = ["ID", "Type", "Loc (z,y,x)", "Size (vox)", "Eq.dia", "Peak d", "Severity"]
    widths = [16, 30, 40, 24, 20, 22, 38]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(*NAVY)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, widths):
        pdf.cell(w, 7, h, border=0, align="C", fill=True)
    pdf.ln(7)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 9)
    if not confirmed:
        pdf.cell(sum(widths), 7, "  (none confirmed)", border="B")
        pdf.ln(9)
        return

    for i, d in enumerate(sorted(confirmed, key=lambda x: x["severity_score"], reverse=True)):
        pdf.set_fill_color(*(LIGHT if i % 2 == 0 else (255, 255, 255)))
        z, y, x = d["center_zyx"]
        cells = [
            d["detection_id"], d["final_type"],
            f"{z:.0f}, {y:.0f}, {x:.0f}",
            str(d["size_voxels"]), f"{d['equivalent_diameter']:.1f}",
            f"{d['intensity_delta']:+.0f}", "",
        ]
        for c, w in zip(cells, widths[:-1]):
            pdf.cell(w, 6.5, f" {c}", border=0, fill=True)
        # Severity cell with a coloured chip.
        x0 = pdf.get_x()
        pdf.cell(widths[-1], 6.5, "", border=0, fill=True)
        r, g, b = SEV_COLORS[d["severity_label"]]
        pdf.set_fill_color(r, g, b)
        pdf.rect(x0 + 2, pdf.get_y() + 1.5, 3.5, 3.5, style="F")
        pdf.set_text_color(0, 0, 0)
        pdf.set_xy(x0 + 7, pdf.get_y())
        pdf.cell(widths[-1] - 7, 6.5, f"{d['severity_label']} ({d['severity_score']:.0f})")
        pdf.ln(6.5)
    pdf.ln(3)


def _image_page(pdf, title, image_path, caption):
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    if image_path.exists():
        pdf.image(str(image_path), x=10, w=190)
    else:
        pdf.cell(0, 8, f"[missing image: {image_path.name}]", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 5, caption)
    pdf.set_text_color(0, 0, 0)


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
def build_report(vol_id):
    common.ensure_dirs(REPORTS_DIR)
    manifest = common.load_json(MANIFESTS_DIR / f"{vol_id}.json")
    review = common.load_json(REVIEWS_DIR / f"{vol_id}.json")
    det = common.load_json(DETECTIONS_DIR / f"{vol_id}.json")
    confirmed = [d for d in review["detections"] if d["review_status"] == "confirmed"]
    confirmed.sort(key=lambda d: d["severity_score"], reverse=True)

    cfg = manifest["config"]
    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(12, 12, 12)
    pdf.add_page()
    _title_block(pdf, vol_id, manifest)

    _kv_section(pdf, "Scan metadata", [
        ("Scan ID", vol_id),
        ("Volume shape (z,y,x)", " x ".join(map(str, manifest["shape"])) + " voxels"),
        ("Data type", "Simulated volumetric scan (acoustic-style amplitude)"),
        ("Simulated noise (std)", f"{cfg['noise_std']:.1f}  (difficulty {cfg['difficulty']:.2f})"),
        ("Detections (pre-review)", det["n_detections"]),
        ("Confirmed / rejected", f"{review['n_confirmed']} / {review['n_rejected']}"
                                 f"   (reviewer: {review['reviewer']})"),
    ])

    _findings_section(pdf, vol_id, confirmed)
    _defects_table(pdf, confirmed)

    # 3D render page.
    render_png = RENDERS_DIR / f"{vol_id}_3d.png"
    _image_page(pdf, "3D defect map", render_png,
                "Detected defects rendered as colour-coded isosurfaces inside the "
                "scanned block (translucent). Colours indicate defect type. "
                "Simulated data.")

    # Slice views for the top severe defects.
    for d in confirmed[:3]:
        sp = SLICES_DIR / f"{vol_id}_{d['detection_id']}.png"
        if sp.exists():
            _image_page(
                pdf, f"Slice views - {d['detection_id']} ({d['final_type']})", sp,
                f"Axial / coronal / sagittal slices through the {d['final_type']} at "
                f"(z,y,x)=({d['center_zyx'][0]:.0f}, {d['center_zyx'][1]:.0f}, "
                f"{d['center_zyx'][2]:.0f}). Green box = detected bounding box. "
                f"Equivalent diameter {d['equivalent_diameter']:.1f} voxels, "
                f"severity {d['severity_label']}.")

    out_path = REPORTS_DIR / f"{vol_id}_report.pdf"
    pdf.output(str(out_path))
    print(f"{vol_id}: report -> {out_path.relative_to(common.REPO_ROOT)} "
          f"({review['n_confirmed']} confirmed defects, {pdf.page_no()} pages)")
    return out_path


def main():
    p = argparse.ArgumentParser(description="Generate a client-style PDF inspection report.")
    p.add_argument("--vol", default="vol_000", help="volume id (default vol_000)")
    p.add_argument("--all", action="store_true", help="build a report for every volume")
    args = p.parse_args()
    if args.all:
        for mpath in sorted(MANIFESTS_DIR.glob("*.json")):
            build_report(common.load_json(mpath)["volume_id"])
    else:
        build_report(args.vol)


if __name__ == "__main__":
    main()
