"""Phase 5 - end-to-end pipeline runner.

Generates volumes, detects + measures defects, trains the type classifier,
renders 3D + slice views with human-in-the-loop (auto) review, and builds a
PDF report per scan. Also refreshes the metrics block in README.md from the
actual run, so every published number is measured, never hand-entered.

Usage:
    python run_all.py                 # full run, 20 volumes, GIF for one demo
    python run_all.py -n 8 --no-gif   # smaller/faster run
"""

from __future__ import annotations

import argparse
import re
import shutil
import time
from collections import Counter

import common
from common import DEFECT_TYPES, MANIFESTS_DIR, DATA_DIR, REPO_ROOT

DOCS_DIR = REPO_ROOT / "docs"

import generate_volume
import detect
import classify
import visualize
import report
import make_results


def _pick_gif_volume() -> str:
    """Choose a clear (low-difficulty) volume that shows the most defect types."""
    best, best_key = "vol_000", (-1, 1.0)
    for mpath in sorted(MANIFESTS_DIR.glob("*.json")):
        m = common.load_json(mpath)
        n_types = len(set(d["type"] for d in m["defects"]))
        diff = m["config"]["difficulty"]
        key = (n_types, -diff)  # more types, then easier
        if key > best_key:
            best_key, best = key, m["volume_id"]
    return best


def run_pipeline(n_volumes=20, seed=42, make_gif=True):
    t0 = time.time()

    print("=" * 70, "\n[1/5] Generating synthetic volumes\n" + "=" * 70)
    generate_volume.generate_set(n_volumes, seed, make_previews=True)

    print("\n" + "=" * 70, "\n[2/5] Detecting + measuring defects\n" + "=" * 70)
    detect.run(detect.DetectConfig())

    print("\n" + "=" * 70, "\n[3/5] Training defect-type classifier\n" + "=" * 70)
    classify.train_and_evaluate()
    classify.annotate_all()

    print("\n" + "=" * 70, "\n[4/5] Rendering 3D + slices, human-in-the-loop (auto) review\n" + "=" * 70)
    gif_vol = _pick_gif_volume() if make_gif else None
    for mpath in sorted(MANIFESTS_DIR.glob("*.json")):
        vid = common.load_json(mpath)["volume_id"]
        visualize._process_one(vid, gif=(vid == gif_vol), auto_review=True)
    if gif_vol:
        print(f"  demo orbit GIF: {gif_vol}")

    print("\n" + "=" * 70, "\n[5/5] Building PDF inspection reports\n" + "=" * 70)
    for mpath in sorted(MANIFESTS_DIR.glob("*.json")):
        report.build_report(common.load_json(mpath)["volume_id"])

    export_demo_assets(gif_vol)
    update_readme_metrics(gif_vol)
    make_results.build()
    print(f"\nDone in {time.time() - t0:.1f}s. Outputs under {DATA_DIR.relative_to(REPO_ROOT)}/")


def export_demo_assets(gif_vol):
    """Copy a small curated set of showcase assets into docs/ for the README.

    The bulk of data/ is regenerable and gitignored; only these committed
    assets back the README on a public repo.
    """
    common.ensure_dirs(DOCS_DIR)
    demo = gif_vol or "vol_000"

    def _cp(src, dst):
        if src.exists():
            shutil.copyfile(src, DOCS_DIR / dst)

    _cp(DATA_DIR / "metrics_curve.png", "metrics_curve.png")
    _cp(DATA_DIR / "renders" / f"{demo}_3d.png", "demo_3d.png")
    _cp(DATA_DIR / "renders" / f"{demo}_3d.gif", "demo_3d.gif")
    _cp(DATA_DIR / "previews" / f"{demo}.png", "sample_preview.png")
    _cp(DATA_DIR / "reports" / f"{demo}_report.pdf", "sample_report.pdf")

    # A slice montage for the most severe confirmed defect of the demo volume.
    review = common.load_json(DATA_DIR / "reviews" / f"{demo}.json")
    confirmed = [d for d in review["detections"] if d["review_status"] == "confirmed"]
    if confirmed:
        top = max(confirmed, key=lambda d: d["severity_score"])
        _cp(DATA_DIR / "slices" / f"{demo}_{top['detection_id']}.png", "sample_slices.png")
    print(f"Exported demo assets (from {demo}) to {DOCS_DIR.relative_to(REPO_ROOT)}/")


def update_readme_metrics(gif_vol=None):
    """Rewrite the auto-generated metrics block in README.md from JSON results."""
    readme = REPO_ROOT / "README.md"
    if not readme.exists():
        return
    m = common.load_json(DATA_DIR / "metrics_summary.json")
    c = common.load_json(DATA_DIR / "classifier_metrics.json")

    # Aggregate ground-truth composition for context.
    type_counts = Counter()
    n_vol = 0
    for mp in sorted(MANIFESTS_DIR.glob("*.json")):
        man = common.load_json(mp)
        n_vol += 1
        type_counts.update(d["type"] for d in man["defects"])

    t = m["totals"]
    lines = [
        "<!-- METRICS:START (auto-generated by run_all.py - do not edit by hand) -->",
        f"_Measured over {n_vol} generated volumes ({t['n_gt']} planted defects), "
        f"IoU match threshold {m['config']['iou_match_threshold']}._",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Detection recall | **{m['recall']:.3f}** ({t['tp']}/{t['n_gt']}) |",
        f"| Detection precision | **{m['precision']:.3f}** ({t['tp']}/{t['n_detections']}) |",
        f"| F1 | {m['f1']:.3f} |",
        f"| False positives (total) | {m['false_positives']} |",
        f"| Mean IoU (matched) | {m['mean_iou_matched']:.3f} |",
        f"| Centroid localization error | {m['mean_centroid_error_voxels']:.2f} voxels |",
        f"| Diameter sizing error (median) | {m['median_diameter_abs_error_frac']*100:.1f}% "
        f"(bias {m['median_diameter_bias_frac']*100:+.1f}%) |",
        f"| Type classifier accuracy (5-fold CV) | **{c['cv_accuracy']*100:.1f}%** "
        f"(heuristic baseline {c['heuristic_accuracy']*100:.1f}%) |",
        f"| Detection throughput | {t['n_gt']+m['false_positives']} regions in "
        f"{m['total_time_sec']:.1f}s over {n_vol} volumes |",
        "",
        "Per-type detection recall:",
        "",
        "| Defect type | Recall | Planted |",
        "|---|---|---|",
    ]
    for ty in DEFECT_TYPES:
        r = m["per_type_recall"][ty]
        lines.append(f"| {ty} | {r:.2f} | {m['per_type_counts'][ty]['planted']} |")
    lines += [
        "",
        "![Detection vs difficulty](docs/metrics_curve.png)",
        "<!-- METRICS:END -->",
    ]
    block = "\n".join(lines)

    text = readme.read_text()
    pattern = re.compile(r"<!-- METRICS:START.*?METRICS:END -->", re.DOTALL)
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        text += "\n\n" + block + "\n"
    readme.write_text(text)
    print("Updated README.md metrics block.")


def main():
    p = argparse.ArgumentParser(description="Run the full VoxelScan pipeline end to end.")
    p.add_argument("-n", "--n-volumes", type=int, default=20)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--no-gif", action="store_true", help="skip the demo orbit GIF")
    args = p.parse_args()
    run_pipeline(args.n_volumes, args.seed, make_gif=not args.no_gif)


if __name__ == "__main__":
    main()
